---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minecraft-bedrock-server.fullname" . }}
  labels:
    {{- include "minecraft-bedrock-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage | quote }}
