# Default values for minecraft-bedrock-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The EULA must be accepted for the pod to be sucessfully deployed
eula: false

config: {}
  # # Must accept the EULA to use the Minecraft server. Set this value *or*
  # # set `eula: true` above
  # # Default: FALSE Options: TRUE, FALSE
  # EULA: "TRUE"
  #
  # # Sets the game mode for new players.
  # # Default: survival Options: survival, creative, adventure
  # GAMEMODE: "survival"
  # # Sets the difficulty of the world.
  # # Default: easy Options: peaceful, easy, normal, hard
  # DIFFICULTY: "easy"
  # # Permission level for new players joining for the first time.
  # # Options: visitor, member, operator
  # DEFAULT_PLAYER_PERMISSION_LEVEL: "member"
  # # Determines the type of map that is generated.
  # # Default: DEFAULT Options: FLAT, LEGACY, DEFAULT
  # LEVEL_TYPE: "DEFAULT"
  # # If true then cheats like commands can be used.
  # # Default: false Options: true, false
  # ALLOW_CHEATS: false
  # # The maximum number of players that can play on the server.
  # # Default: 10
  # MAX_PLAYERS: "10"
  # # After a player has idled for this many minutes they get kicked.
  # # Default: 30
  # PLAYER_IDLE_TIMEOUT: "30"
  # # Force clients to use texture packs in the current world.
  # # Default: false Options: true, false
  # TEXTUREPACK_REQUIRED: "false"
  # # Use to randomize the world.
  # # Default: *empty*
  # LEVEL_SEED: "33480944"
  #
  # # Changing these will have a security impact
  #
  # # If true then all connected players must be authenticated to Xbox Live.
  # # Default: true Options: true, false
  # ONLINE_MODE: "true"
  # # If true then all connected players must be listed in the separate
  # # whitelist.json file.
  # # Default: false, Options: true, false
  # WHITE_LIST: "false"
  #
  # # Changing these will have a performance impact
  #
  # # The maximum allowed view distance in number of chunks.
  # # Default: 10
  # VIEW_DISTANCE: "10"
  # # The world is ticked this many chunks away from any player.
  # # Default: 4 Options: 4-12
  # TICK_DISTANCE: "4"
  # # Maximum number of threads the server tries to use. If set to 0 or removed
  # # then it uses as many as possible.
  # # Default: 8
  # MAX_THREADS: "8"
  #
  # # These values shouldn't be modified unless you know what you're doing
  #
  # # The "level-name" value is used as the world name and its folder name. The
  # # player may also copy their saved game folder here, and change the name to
  # # the same as that folder's to load it instead.
  # # Default: level
  # LEVEL_NAME: "level"
  # # Used as the server name.
  # # Default: Dedicated Server
  # SERVER_NAME: "Dedicated Server"
  # # Which IPv4 port the server should listen to.
  # # Default: 19132
  # SERVER_PORT: 19132

storage: "1Gi"

image:
  repository: itzg/minecraft-bedrock-server
  pullPolicy: Always
  tag: latest

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 19132
  ipFamily: IPv4
  annotations: {}
    # # If using Metallb and `type: LoadBalancer`, you can share multiple
    # # server instances on one IP address by overriding `service.port` and
    # # setting:
    # metallb.universe.tf/allow-shared-ip: minecraft-lb

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
